name: Release to Mozilla
on:
  workflow_dispatch

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Python 3.10
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.10.11
          architecture: x64

      - name: Build and pack
        run: python3 build.py xpi
        
      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ecsta-firefox.zip
          path: dist/ecsta-firefox.zip
          
      - name: WebExtPublish: Firefox
        uses: maoserr/firefox_extension_publish@v1.0.4
        with:
          # Extension ID.
          firefox_extension_id: Ecsta@kckarnige.github.io
          # API key from Mozilla
          api_key: ${{ secrets.JWT_ISSUER }}
          # API secret from Mozilla
          api_secret: ${{ secrets.JWT_SECRET }}
          # Zip file for firefox extension
          file: dist/ecsta-firefox.zip
          # Zip file for source upload
          #src_file: # optional