name: Draft Release # Stole this from Oculus Dummy, which stole from ArmCord
on:
  workflow_dispatch

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Python 3.10
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.10.11
          architecture: x64

      - name: Build and pack for Firefox
        run: python3 build.py xpi
        
      - name: Build and pack for Chromium
        run: python3 build.py crx
        
      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ecsta-firefox.xpi
          path: dist/ecsta-firefox.xpi
          
      - name: Upload Chromium Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ecsta-chromium.crx
          path: dist/ecsta-chromium.crx

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: ecsta-chromium.crx
          path: release
          
      - uses: actions/download-artifact@v2
        with:
          name: ecsta-firefox.xpi
          path: release    

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'manifest.xpi.json'
          prop_path: 'version'

      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: devbuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: devbuild
          name: Ecsta - Test build ${{steps.version.outputs.prop}} 
          draft: false
          prerelease: true
          body_path: .github/release.md
          files: |
            release/ecsta-chromium.crx
            release/ecsta-firefox.xpi
